### ISSUE TITLE
TypeError: Cannot compare two different types

### ISSUE THREAD

**Issue by justtryingthingsout** [virchau13/pcse#4]
**Describe the bug**

`TypeError: Cannot compare two different types` even when both types are `REAL`

**Code required to reproduce**
The pseudocode that you used to trigger the bug.

```
DECLARE w:REAL
DECLARE h:REAL
DECLARE hs:REAL
DECLARE bmi:REAL

OUTPUT "Please enter your weight in kg:"
INPUT w

OUTPUT "Please enter you height in cm:"
INPUT h

h <- h/100

hs <- h*h

bmi <- w/hs

OUTPUT "Your bmi is ", bmi

IF bmi < 18.5
THEN
    OUTPUT "You are underweight"
ELSE
    IF 25.0 > bmi < 18.0
    THEN
        OUTPUT "You are normal weight"
    ELSE
        IF 30.0 > bmi < 25.0
        THEN
            OUTPUT "You are overweight"
        ELSE
            IF bmi > 30.0
            THEN
                OUTPUT "You are obese"
            ENDIF
        ENDIF
    ENDIF
ENDIF
```

**Expected behavior**

It outputs the string

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/31097061/95170479-15d43280-07e7-11eb-9018-e968d64a1d40.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Architecture [e.g. 64 bit]

OS: macOS
Architecture: 64 bit Intel

**Additional context**

**Comment by virchau13** [comment]
Thanks for submitting this issue!

However, your pseudocode appears to be incorrect.
See this line:
```
IF 25.0 > bmi < 18.0
```
This evaluates to
```
IF (25.0 > bmi) < 18.0
```
` (25.0 > bmi)` is of type BOOLEAN and `18.0` is of type REAL, so you are indeed comparing a BOOLEAN and a REAL.

If you want to make your program not error, you must write:
```
IF 25.0 > bmi AND bmi < 18
```

In any case, thank you again for taking the time to report something! If you have any other issues, feel free to report them.
