### ISSUE TITLE
Better error msg output

### ISSUE THREAD

**Issue by mohan10216** [virchau13/pcse#6]
Try adding in a functionality to identify the line in which an error has occurred.

**Comment by virchau13** [comment]
This functionality is already present through the `-l` flag; run `pcse -l <file>` to use it. It was turned off by default to help students learn how to debug code without line numbers (since in an exam, there is no interpreter to help.)

**Comment by mohan10216** [comment]
> This functionality is already present through the `-l` flag; run `pcse -l <file>` to use it. It was turned off by default to help students learn how to debug code without line numbers (since in an exam, there is no interpreter to help.)

When I run `./pcse` I get a permission error, and when I run `pcse -l <file>` with the <,>, I get the error zsh: parse error near `\n'.EVen with the full path, the sam error occurs. How do I resolve this?

**Comment by virchau13** [comment]
To be more specific, if your file is named `fname.pcse`, then build pcse first using the instructions in the README and then run `./pcse -l fname.pcse`.

**Comment by mohan10216** [comment]
I have already Built it, however it outputs the same error, `zsh: permission denied: ./`. This is what I got after running `make`: 
`Consolidate compiler generated dependencies of target pcse
[ 50%] Building CXX object CMakeFiles/pcse.dir/src/main.cpp.o
warning: unknown warning option '-Wno-class-memaccess'; did you mean '-Wno-class-varargs'? [-Wunknown-warning-option]
In file included from /Users/ajaymohan/pcse/src/main.cpp:1:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iostream:37:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/ios:215:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__locale:14:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:504:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string_view:175:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__string:57:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:643:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:659:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:1480:9: error: implicit instantiation of undefined template 'BinExpr<0>'
        ++__i;
        ^
/Users/ajaymohan/pcse/src/parser.hpp:144:19: note: in instantiation of member function 'std::__1::__wrap_iter<BinExpr<0> *>::operator++' requested here
                        for(Expr& expr : *lv.indexes){
                                       ^
/Users/ajaymohan/pcse/src/parser.hpp:103:7: note: template is declared here
class BinExpr;
      ^
In file included from /Users/ajaymohan/pcse/src/main.cpp:1:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iostream:37:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/ios:215:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__locale:14:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:504:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string_view:175:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__string:57:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:643:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:659:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:1480:9: error: implicit instantiation of undefined template 'Stmt<false>'
        ++__i;
        ^
/Users/ajaymohan/pcse/src/parser.hpp:592:21: note: in instantiation of member function 'std::__1::__wrap_iter<const Stmt<false> *>::operator++'
      requested here
                for(const auto& x : b.stmts){
                                  ^
/Users/ajaymohan/pcse/src/parser.hpp:19:7: note: template is declared here
class Stmt;
      ^
In file included from /Users/ajaymohan/pcse/src/main.cpp:1:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iostream:37:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/ios:215:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__locale:14:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:504:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string_view:175:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__string:57:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:643:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:659:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:1480:9: error: implicit instantiation of undefined template 'Stmt<true>'
        ++__i;
        ^
/Users/ajaymohan/pcse/src/parser.hpp:613:21: note: in instantiation of member function 'std::__1::__wrap_iter<const Stmt<true> *>::operator++'
      requested here
                for(const auto& x : p.stmts){
                                  ^
/Users/ajaymohan/pcse/src/parser.hpp:19:7: note: template is declared here
class Stmt;
      ^
In file included from /Users/ajaymohan/pcse/src/main.cpp:3:
/Users/ajaymohan/pcse/src/interpreter.hpp:622:23: error: cannot increment value of type 'std::__1::__wrap_iter<const Stmt<false> *>'
        for(const auto& stmt : stmts){
                             ^
/Users/ajaymohan/pcse/src/interpreter.hpp:622:25: note: in implicit call to 'operator++' for iterator of type 'const std::__1::vector<Stmt<false>,
      std::__1::allocator<Stmt<false> > >'
        for(const auto& stmt : stmts){
                               ^~~~~
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:624:54: note: selected 'begin' function with iterator type
      'std::__1::vector<Stmt<false>, std::__1::allocator<Stmt<false> > >::const_iterator' (aka '__wrap_iter<const Stmt<false> *>')
    _LIBCPP_INLINE_VISIBILITY const_iterator         begin()   const _NOEXCEPT;
                                                     ^
In file included from /Users/ajaymohan/pcse/src/main.cpp:3:
/Users/ajaymohan/pcse/src/interpreter.hpp:637:23: error: cannot increment value of type 'std::__1::__wrap_iter<const Stmt<true> *>'
        for(const auto& stmt : stmts){
                             ^
/Users/ajaymohan/pcse/src/interpreter.hpp:637:25: note: in implicit call to 'operator++' for iterator of type 'const std::__1::vector<Stmt<true>,
      std::__1::allocator<Stmt<true> > >'
        for(const auto& stmt : stmts){
                               ^~~~~
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:624:54: note: selected 'begin' function with iterator type
      'std::__1::vector<Stmt<true>, std::__1::allocator<Stmt<true> > >::const_iterator' (aka '__wrap_iter<const Stmt<true> *>')
    _LIBCPP_INLINE_VISIBILITY const_iterator         begin()   const _NOEXCEPT;
                                                     ^
1 warning and 5 errors generated.
make[2]: *** [CMakeFiles/pcse.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/pcse.dir/all] Error 2
make: *** [all] Error 2`

**Comment by virchau13** [comment]
Huh, that's interesting... I thought I fixed the compile issue on Apple Clang. What's the output of `git rev-parse HEAD`?

**Comment by mohan10216** [comment]
This is the output `ad51f9a6f365ac52524ee16e921cec40f9797ea3`.

**Comment by virchau13** [comment]
You're trying to compile an outdated version of pcse. Try executing `git pull` to update your local version and try building it again.

**Comment by mohan10216** [comment]
Ok I have done it, what do I do now?

**Comment by virchau13** [comment]
Follow the instructions from earlier.

> To be more specific, if your file is named `fname.pcse`, then build pcse first using the instructions in the README and then run `./pcse -l fname.pcse`.

**Comment by mohan10216** [comment]
It still says permission denied. Look at the images below:
<img width="1070" alt="Screenshot 2022-01-27 at 8 53 55 AM" src="https://user-images.githubusercontent.com/55964081/151272372-18878434-c4f6-44c5-a209-511d17dcb9c1.png">
<img width="1091" alt="Screenshot 2022-01-27 at 8 56 02 AM" src="https://user-images.githubusercontent.com/55964081/151272378-59900059-b23c-4eb2-a7dc-e7134b235f5e.png">
<img width="1075" alt="Screenshot 2022-01-27 at 8 57 20 AM" src="https://user-images.githubusercontent.com/55964081/151272382-0382aa6e-4023-4165-809c-421c3c95f612.png">
<img width="1055" alt="Screenshot 2022-01-27 at 8 59 03 AM" src="https://user-images.githubusercontent.com/55964081/151272383-5098f952-2c9d-4011-98c9-56fcb58ad987.png">

**Comment by mohan10216** [comment]
Is the problem because I built another pcse inside of the existing pcse?

**Comment by virchau13** [comment]
Maybe try `chmod +x ./pcse` and then run the command?

**Comment by mohan10216** [comment]
Same error:
<img width="437" alt="Screenshot 2022-01-27 at 11 36 10 AM" src="https://user-images.githubusercontent.com/55964081/151287678-bfc10bb5-e5ca-452b-8880-949af09adfd3.png">

**Comment by virchau13** [comment]
Okay, I think I know the problem: it's because I didn't fix the compiler for _Apple_ Clang, I fixed it for clang on Linux. Give me a bit to fix the compiler on Apple Clang and I'll report back. In the meantime, you can try invoking `pcse` from the VSCode extension directly, by copying the path it outputs in the terminal and invoking it via <code><i>pcse-path</i> -l <i>yourfile.pcse</i></code>.

**Comment by mohan10216** [comment]
@virchau13 Any update?

**Comment by mohan10216** [comment]
@virchau13 Any progress?
